env:
  global:
  - secure: fyd6c/A8k4tKK0LVbq87pxdNz0KuSe0CyT5KvuA5tbIBSMGHLGdaMTgjk/nmIFtWM76DR2yBrNeDFMkTr47yKhUoMMDAnrbwpnjik2vqM7OvSi5a+cxtis9dxO0K2znHcUv1YQtUHnLZyaIlgJtEEMlrWv3EmltUEhbiZ2C6LrQ=
  - secure: BlExRq1ziUsLwpgHwDuh1d/QIsuBsvKR28d6yIru77RbLB9aiFxS9c2w0rXgNR31/mcqSS0QHGxjYJIMvHF+7J7KOBLIUSQw1TNNtVmshTIUrfhTWraoORlMJlZLkAh4bj91dGCTq7186qiVIVEfPVMPGvj3wHBenkyW/wtd+tA=
  - secure: eg0K64dtqY9bOEXccNbP+LhFESeUYhLCD0t0c189P7e0uDgjgtTADpWnGs5yKfgfGmRXGOXdbZlCbJoq38aEY9V6SlfJRHPKY7Eg3PNcVoJH/VugIGbVYJ5kH3PS6loKhSYBOVwS6btFNA31YNeTF5bXoHYBC7/xGG+RJdGkqF4=
  - secure: TGhsRuMO1zEKk3SlzEhTMBU5DOxJN6zbtgzA4ZXz1CyDRYAO+Mhw3qrnOK0o29kFwSO7UjOhwuAbHvlMwhG90JDt4tR5gLPoCR96od7I33ysDVwXNzTj+KXEp2HSmRvz2dxoxgjlajSdEHtAk7yUFkPlAkmnQKF0S72/fS8xU7k=
  - secure: axh2vYKSWov500Fg4RohyMgrDcrkrnkKZfR63UBnF0lJNFrfxS82CpbIK0aPumLto3+pH5AHVnyWKiHyq+/vklfaoBgw4fn7BxMiC65kK+94AIW/dCntgCVXECTFPEy5uFf8gNGaFD4aAbomD7ph4qudNQxwVDaYAeb21h7q13U=

branches:
  only:
    - master

notifications:
  email: false

language: python

install:
  - pip install icalendar
  - pip install pytz
  - mkdir ${TRAVIS_BUILD_DIR}/html
  - cd ${TRAVIS_BUILD_DIR}/html
  - git config --global user.email "${GIT_MAIL}"
  - git config --global user.name "${GIT_USER}"
  - git clone https://${GH_TOKEN}@github.com/KalleDK/IHACal . > /dev/null 2>&1

script:
  - cd ${TRAVIS_BUILD_DIR}/html
  - ./update.sh courses.lst $ICAL_USER $ICAL_PASS

after_success:
  - cd ${TRAVIS_BUILD_DIR}/html
  - cat Readme.md
  - git add -f .
  - git commit -m "Travis CI [ci skip]"
  - git remote set-url origin https://${GH_TOKEN}@github.com/KalleDK/IHACal
  - git remote -v
  - git push -fq origin  master
