ihacal:
   build: .

   environment:
     - USERNAME
     - PASSWORD
     - DAYCOUNT=140

   volumes:
     - ./README.md:/usr/src/app/README.md:Z

ihabah:
   build: .

   volumes:
     - /usr/bin/vi:/usr/bin/vi:Z
     - ./app:/usr/src/app:Z
     - ./README.md:/usr/src/app/README.md:Z

   entrypoint:
     - /bin/bash

   environment:
     - USERNAME
     - PASSWORD
     - DAYCOUNT=140
